### ISSUE TITLE
Specification document misattributed

### ISSUE THREAD

**Issue by briancaine** [skycoin/cx#2]
So I clicked the [Specification link](http://cx.skycoin.net/assets/cx.pdf) on cx.skycoin.net.

Several of the authors' names caught my eye. It seems like someone left the byline intact from the previous document.

The byline is in [this file](https://github.com/skycoin/cx/blob/master/documentation/specification/first.tex).

**Comment by amherag** [comment]
Hi Brian,

Yeah, I haven't touched that document in so long. I took scheme's latex source code and decided to use it as CX's template. I remember that I didn't even want to change the author's names because back then I didn't know if someone else was going to join in CX's design. I should remove it, and upload something better later on.

**Comment by briancaine** [comment]
Yeah, I figured as much. Just bringing it to someone's attention.

**Comment by amherag** [comment]
I removed the link for now. Thanks a lot for your time :D
