### ISSUE TITLE
mouse movement events prevent other events from firing

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#92]
when i had all different input events (mouse motion, mouse buttons, key press/releases) printing out strings everytime they were fired, 
i couldn't get any mouse button press events to trigger while the mouse was moving.

also i think keyboard press/release events were blocked as well.

**Comment by asahi3g** [comment]
I think i know what's happening but i'm not sure yet on how to fix it.
When glfw.PollEvents() is called, All events gathered between the last time it was call are fired : go callbacks are fired
CX/Native -> glfw.PollEvents
-----> GO window.PollEvents()
--------> iterates through all events and fire the callback for each one
------------> GO callback which expand the CX call stack and create a new CX call to CX function passed by the user.

If there are more than one event fired, this actually create a recursive hierarchy.
CX user callback calls will be nested and called in reverse order
And it breaks the program control flow (eating the first expression of the CX user callback) when popping the stack.

One solution could be to generate a dummy CX function declaration at runtime and then register these calls as child expressions (instead of appending a new call in the callstack).

cx/op_glfw.go line 106 looks like a workaround to avoid recursive calls.
```
// if prgrm.CallStack[prgrm.CallCounter].Operator == fn {
			// 	return
}
```

**Comment by corpusc** [comment]
seems to work great now for what i'm doing!  no button clicks seem to get skipped.

not sure if your commit titled "Fixed callback execution : issue 92" means this should be closed now.  
it sounds like fully fixing it might be tricky.  according to your notes here.
